### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by LorenzHenk** [tchayen/markdown-links#68]
Hi, I started trying out foam, but I wasn't able to get the graph working correctly. It even won't work with the markdown-links examples.

Did I miss something?

```
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Markdown links v0.8.0
```

![grafik](https://user-images.githubusercontent.com/10603631/96505855-ff9e8b80-1256-11eb-9da6-2c832991afa9.png)

**Comment by tchayen** [comment]
Hi, thanks for reporting this!

Could you please try opening the extension's developer console and checking what error it gives?

I think that it might be related to system file paths or something like this, but I can't check it at the moment.

**Comment by ingalless** [comment]
@tchayen just because I spotted it, this is running in WSL, the Windows Subsystem for Linux. In case that may be interfering...

**Comment by LorenzHenk** [comment]
![grafik](https://user-images.githubusercontent.com/10603631/96640618-ba945b00-1323-11eb-80d4-6abb805279ac.png)

```
mainThreadExtensionService.ts:65 [[object Object]]Cannot find module '@thomaskoppelaar/markdown-it-wikilinks'
Require stack:
- /home/lorenz/.vscode-server/extensions/kortina.vscode-markdown-notes-0.0.20/out/MarkdownRenderingPlugin.js
- /home/lorenz/.vscode-server/extensions/kortina.vscode-markdown-notes-0.0.20/out/extension.js
- /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/loader.js
- /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/bootstrap-amd.js
- /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/bootstrap-fork.js
$onExtensionRuntimeError @ terminalInstanceService.ts:31


mainThreadExtensionService.ts:66 Error: Cannot find module '@thomaskoppelaar/markdown-it-wikilinks'
Require stack:
- /home/lorenz/.vscode-server/extensions/kortina.vscode-markdown-notes-0.0.20/out/MarkdownRenderingPlugin.js
- /home/lorenz/.vscode-server/extensions/kortina.vscode-markdown-notes-0.0.20/out/extension.js
- /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/loader.js
- /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/bootstrap-amd.js
- /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793)
	at Function.Module._load (internal/modules/cjs/loader.js:686)
	at Function.t._load (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:1082)
	at Function.i._load (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:1052)
	at Function.n._load (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:1048)
	at Module.require (internal/modules/cjs/loader.js:848)
	at require (internal/modules/cjs/helpers.js:74)
	at Object.pluginSettings (/home/lorenz/.vscode-server/extensions/kortina.vscode-markdown-notes-0.0.20/out/MarkdownRenderingPlugin.js:50)
	at Object.extendMarkdownIt (/home/lorenz/.vscode-server/extensions/kortina.vscode-markdown-notes-0.0.20/out/extension.js:51)
	at Object.extendMarkdownIt (/home/lorenz/.vscode-server/extensions/yzhang.markdown-all-in-one-3.3.0/dist/extension.js:1)
	at processTicksAndRejections (internal/process/task_queues.js:94)
	at async Object.newEngine (/home/lorenz/.vscode-server/extensions/yzhang.markdown-all-in-one-3.3.0/dist/extension.js:1)
```

> @tchayen just because I spotted it, this is running in WSL, the Windows Subsystem for Linux. In case that may be interfering...
Right, I forgot to mention.
I'm using WSL (Ubuntu) on Windows 10.

**Comment by tchayen** [comment]
Hm, those errors seem to be related to other extension (`markdown-notes`). Is there any other info hidden deep down in the logs?

**Comment by LorenzHenk** [comment]
After some time I tried opening another markdown file (double click on the file name in the explorer) and these warnings and errors appeared:

![grafik](https://user-images.githubusercontent.com/10603631/96683136-0bcf3980-137a-11eb-9375-085fc87b9333.png)


```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Webview is disposed
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181


console.ts:137 [Extension Host] stack trace: Error: Webview is disposed	at S.assertNotDisposed (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:875:749)	at S.get webview [as webview] (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:874:699)	at /home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7:6068	at Generator.next (<anonymous>)	at /home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7:4078	at new Promise (<anonymous>)	at n (/home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7:3823)	at /home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7:6030	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45:801)	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:738:869	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45:801)	at b.acceptDocumentsAndEditorsDelta (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:743:650)	at b.$acceptDocumentsAndEditorsDelta (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:741:848)	at m._doInvokeHandler (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:895:464)	at m._invokeHandler (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:895:156)	at m._receiveRequest (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:893:817)	at m._receiveOneMessage (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:892:623)	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:890:691	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45:801)	at v.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:256:381)	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:1084:179	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45:801)	at v.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:256:381)	at t.PersistentProtocol._receiveMessage (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:261:451)	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:258:489	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45:801)	at p.acceptChunk (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:253:851)	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:253:203	at Socket.t (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:263:54)	at Socket.emit (events.js:223:5)	at addChunk (_stream_readable.js:309:12)	at readableAddChunk (_stream_readable.js:290:11)	at Socket.Readable.push (_stream_readable.js:224:10)	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
t.log @ console.ts:70
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181


mainThreadExtensionService.ts:65 [[object Object]]Webview is disposed
$onExtensionRuntimeError @ terminalInstanceService.ts:31
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181


mainThreadExtensionService.ts:66 Error: Webview is disposed
	at S.assertNotDisposed (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:875)
	at S.get webview [as webview] (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:874)
	at /home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7
	at Generator.next (<anonymous>)
	at /home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7
	at new Promise (<anonymous>)
	at n (/home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7)
	at /home/lorenz/.vscode-server/extensions/tchayen.markdown-links-0.8.0/dist/extension.js:7
	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45)
	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:738
	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45)
	at b.acceptDocumentsAndEditorsDelta (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:743)
	at b.$acceptDocumentsAndEditorsDelta (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:741)
	at m._doInvokeHandler (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:895)
	at m._invokeHandler (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:895)
	at m._receiveRequest (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:893)
	at m._receiveOneMessage (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:892)
	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:890
	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45)
	at v.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:256)
	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:1084
	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45)
	at v.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:256)
	at t.PersistentProtocol._receiveMessage (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:261)
	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:258
	at l.fire (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:45)
	at p.acceptChunk (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:253)
	at /home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:253
	at Socket.t (/home/lorenz/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:263)
	at Socket.emit (events.js:223)
	at addChunk (_stream_readable.js:309)
	at readableAddChunk (_stream_readable.js:290)
	at Socket.Readable.push (_stream_readable.js:224)
	at TCP.onStreamRead (internal/stream_base_commons.js:181)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:535
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
```

**Comment by LorenzHenk** [comment]
Is there any other place I should check for logs?

**Comment by RyanPersson** [comment]
Hi @LorenzHenk , I use this extension successfully in WSL-2, along with the markdown-notes extension.  (and several of the other markdown related extensions it looks like you're using from the logs.)

What's your full list of extensions currently enabled?   I'd be down to try & recreate this bug in my env & figure out what's causing it.

**Comment by LorenzHenk** [comment]
When trying out I always had another vs code window open with a ReactJS project. When opening the graph, it seems like it also checked that project and its `node_modules` directory. (TBH I don't know if this is really what's going on, but it's my best guess)

I just did a quick test and indeed, when installing the node packages in the markdown-links repo and then running the vs-code command `Show Graph`, it takes significantly longer until the graph is shown. This means the extension really processes the `node_modules` directory.

I just ran `Show Graph` in my ReactJS project and it threw the following error: _Command 'Markdown Links: Show Graph' resulted in an error ([UriError]: Scheme contains illegal characters.)_
I guess this happens due to a malformed markdown file in `node_modules`.


I propose that the `markdown-links` extension should omit paths listed in `.gitignore` (e.g. `node_modules`).

**Comment by LorenzHenk** [comment]
Seems like this is a known problem: https://github.com/tchayen/markdown-links/issues/33

I'll close the issue since it seems like this was the root cause of the issues.

Thanks everybody for your help!

**Comment by tchayen** [comment]
@LorenzHenk `.gitignore` or other sane defaults are definitely a must. Will look into getting it right, as there were several approaches and/or partial fixes that never got rid of the problem.

That should indeed help with this case, it is also a known problem with markdown parser exploding on some specific links (#40, #45).
